oidc:
  hostname:
    name: rhsso-rhsso-gateway-prod-525eca1d5089dbdc-istio-system.apps.cluster-jzbs4.jzbs4.sandbox1713.opentlc.com
    # Set this to `true` if Keycloak server is using https, otherwise, set to false.
    secure: true
  client:
    id: flask-app
    secret: 96f11b88-4be7-4fe5-a329-ea770d04d2ea
  realm: pysaar

backend:
  service:
    name: uid-server
    port: 8080
    targetPort: 5000
  resources:
    requests:
      memory: "128Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

frontend:
  service:
    name: webserver
    port: 8080
    targetPort: 5000
  resources:
    requests:
      memory: "128Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  config:
    path: /app
    name: client_secrets
