apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: uid-verify
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  action: DENY
  rules:
  - from:
    - source:
        notRequestPrincipals: ["*"]
