apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: jwt-validation
  namespace: webserver
spec:
  selector:
    matchLabels:
      app: uid-server
  jwtRules:
  - issuer: {{ include "oidc.url" . }}/auth/realms/{{ .Values.oidc.realm }}
    jwksUri: {{ include "oidc.url" . }}/auth/realms/{{ .Values.oidc.realm }}/protocol/openid-connect/certs
