apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: webserver
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - "*"
  gateways:
  - webserver-gateway
  http:
  - match:
    - uri:
        exact: /
    - uri:
        exact: /private
    - uri:
        exact: /api
    - uri:
        exact: /logout
    - uri:
        prefix: /oidc_callback
    route:
    - destination:
        host: {{ .Values.frontend.service.name }}
        port:
          number: {{ .Values.frontend.service.port }}
