apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: webserver
  labels:
    app: webserver
spec:
  selector:
    matchLabels:
      app: webserver
  replicas: 1
  template:
    metadata:
      labels:
        app: webserver
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - name: apache
          image: docker.io/mkotelni/oidc-flask:0.0.14
          ports:
            - containerPort: 5000
              name: webserver
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
