apiVersion: apps/v1
kind: Deployment
metadata:
  name: uid-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: uid-server
spec:
  selector:
    matchLabels:
      app: uid-server
  replicas: 1
  template:
    metadata:
      labels:
        app: uid-server
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - name: apache
          image: docker.io/mkotelni/uid-flask:0.0.2
          ports:
            - containerPort: {{ .Values.backend.service.targetPort }}
              name: uid-server
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
