apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: webserver
  labels:
    app: webserver
spec:
  selector:
    matchLabels:
      app: webserver
  replicas: 1
  template:
    metadata:
      labels:
        app: webserver
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - name: apache
          image: docker.io/mkotelni/oidc-flask:0.0.18
          env:
          - name: OPENID_REALM
            value: {{ .Values.oidc.realm }}
          - name: OPENID_HOST
            value: {{ .Values.oidc.hostname.name }}
          - name: BACKEND_URL
            value: {{ template "backend.url" . }}
          ports:
            - containerPort: 5000
              name: webserver
          volumeMounts:
            - mountPath: /app/client_secrets.json
              name: oidc-config
              subPath: client_secrets.json
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - configMap:
            defaultMode: 420
            items:
            - key: client_secrets.json
              path: client_secrets.json
            name: oidc-config
          name: oidc-config