apiVersion: apps/v1
kind: Deployment
metadata:
  name: uid-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "backend.labels" . | nindent 8 }}
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - name: uid-server
          image: {{ .Values.backend.image | default docker.io/mkotelni/uid-flask:0.0.2 }}
          ports:
            - containerPort: {{ .Values.backend.service.targetPort }}
              name: uid-server
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
