apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "frontend.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "frontend.labels" . | nindent 8 }}
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - name: webserver
          image: docker.io/mkotelni/oidc-flask:0.0.18
          env:
          - name: OPENID_REALM
            value: {{ .Values.oidc.realm }}
          - name: OPENID_HOST
            value: {{ .Values.oidc.hostname.name }}
          - name: BACKEND_URL
            value: {{ template "backend.url" . }}
          ports:
            - containerPort: {{ .Values.frontend.service.targetPort }}
              name: webserver
          volumeMounts:
            - mountPath: /app/client_secrets.json
              name: oidc-config
              subPath: client_secrets.json
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
      volumes:
        - configMap:
            defaultMode: 420
            items:
            - key: client_secrets.json
              path: client_secrets.json
            name: oidc-config
          name: oidc-config