apiVersion: v1
kind: Service
metadata:
  labels:
    app: uid-server
  name: uid-server
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http-{{ .Values.backend.service.port }}
    port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.targetPort }}
  selector:
    app: uid-server
  sessionAffinity: None
  type: ClusterIP
