apiVersion: v1
kind: Service
metadata:
  labels:
    app: webserver
  name: webserver
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http-{{ .Values.frontend.service.port }}
    port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
  selector:
    app: webserver
  sessionAffinity: None
  type: ClusterIP
