apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
  name: webserver
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http-{{ .Values.frontend.service.port }}
    port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
  selector:
    {{- include "frontend.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
